name: Workflow summary

on:
  schedule:
    - cron: '0 12 * * 2'  
  workflow_dispatch:  # Maakt handmatige triggers mogelijk

jobs:
  manage-data:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variable for JSON file
        run: |
          "FILE_PATH_BUYORDERS=BuyOrders.json" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh

      - name: Debug environment variable
        run: |
          Write-Output "FILE_PATH is: $env:FILE_PATH"
        shell: pwsh

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run script
        env:
          FILE_PATH_BUYORDERS: ${{ env.FILE_PATH_BUYORDERS}}
          API_KEYS: ${{ secrets.APIKEYS }}
        run: |
          python summary.py
